server:
  port: 8889
  servlet:    context-path: /
spring:  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://176.211.22.62:3306/jnoadb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root

#mybatis-plush配置
mybatis-plus:  type-aliases-package: com.jt.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true 

#实现dubbo的配置
dubbo:
  scan:
    basePackages: oa.jn
  application:
    name: provider-user        #服务名称
  registry:
    address: zookeeper://176.211.22.64:2181?backup=176.211.22.64:2182,176.211.22.64:2183
  protocol:
    name: dubbo
    port: 20880

#引入日志信息
logging:
  level: 
    com.jt.mapper: debug 